#!/usr/bin/env python3
"""Rebuild the decision-impact diagnostic from manuscript-level ledgers.

The script never reads model outputs. It derives the raw corrupted FP8-INT8 gap,
the matched-clean-adjusted interaction, and cell-level absolute-AP floor flags
from the validated CSV ledgers distributed with the paper.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

KEY = ["dataset", "model", "corruption", "severity"]
DATASET_ORDER = ["coco", "voc", "kitti", "tt100k"]
DATASET_LABEL = {"coco": "COCO", "voc": "VOC", "kitti": "KITTI", "tt100k": "TT100K"}
MARKERS = {"coco": "o", "voc": "s", "kitti": "^", "tt100k": "D"}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    root = args.root.resolve()

    contrast_path = root / "generated/direct_format_contrast_cells.csv"
    guardrail_path = root / "generated/direct_absolute_guardrail.csv"
    contrast = pd.read_csv(contrast_path)
    guardrail = pd.read_csv(guardrail_path)

    required_contrast = set(KEY + ["delta_q_all", "delta_e_all"])
    required_guardrail = set(KEY + ["precision", "corrupt_ap_native"])
    if not required_contrast.issubset(contrast.columns):
        raise ValueError(f"Missing contrast columns: {sorted(required_contrast - set(contrast.columns))}")
    if not required_guardrail.issubset(guardrail.columns):
        raise ValueError(f"Missing guardrail columns: {sorted(required_guardrail - set(guardrail.columns))}")
    if len(contrast) != 144 or contrast.duplicated(KEY).any():
        raise ValueError("Expected exactly 144 unique direct-format cells")

    contrast = contrast.copy()
    contrast["clean_gap_ap"] = 100.0 * contrast["delta_q_all"]
    contrast["adjusted_interaction_ap"] = 100.0 * contrast["delta_e_all"]
    contrast["raw_corrupt_gap_ap"] = 100.0 * (contrast["delta_q_all"] + contrast["delta_e_all"])

    guardrail = guardrail.copy()
    guardrail["format"] = guardrail["precision"].replace({"int8-entropy": "INT8", "fp8": "FP8"})
    pivot = guardrail.pivot(index=KEY, columns="format", values="corrupt_ap_native").reset_index()
    if not {"INT8", "FP8"}.issubset(pivot.columns):
        raise ValueError("Both INT8 and FP8 corrupted AP are required in every cell")
    pivot["min_corrupt_ap"] = 100.0 * pivot[["INT8", "FP8"]].min(axis=1)
    merged = contrast.merge(pivot[KEY + ["min_corrupt_ap"]], on=KEY, validate="one_to_one")

    raw_positive = int((merged["raw_corrupt_gap_ap"] > 0).sum())
    raw_negative = int((merged["raw_corrupt_gap_ap"] < 0).sum())
    adjusted_positive = int((merged["adjusted_interaction_ap"] > 0).sum())
    adjusted_negative = int((merged["adjusted_interaction_ap"] < 0).sum())
    positive_to_negative = int(((merged["raw_corrupt_gap_ap"] > 0) & (merged["adjusted_interaction_ap"] < 0)).sum())
    negative_to_positive = int(((merged["raw_corrupt_gap_ap"] < 0) & (merged["adjusted_interaction_ap"] > 0)).sum())
    below_10_cells = int((merged["min_corrupt_ap"] < 10).sum())
    below_5_cells = int((merged["min_corrupt_ap"] < 5).sum())

    # Internal algebraic checks.
    if raw_positive != 134 or raw_negative != 10:
        raise ValueError(f"Unexpected raw-gap sign inventory: {raw_positive}/{raw_negative}")
    if positive_to_negative != 56 or negative_to_positive != 0:
        raise ValueError("Unexpected clean-adjustment interpretation-change inventory")
    if below_10_cells != 18 or below_5_cells != 5:
        raise ValueError("Unexpected cell-level absolute-AP floor inventory")

    output_csv = root / "generated/decision_impact_cells.csv"
    output_tex = root / "generated/decision_impact_summary.tex"
    output_json = root / "generated/decision_impact_audit.json"
    output_pdf = root / "figures/fig_decision_impact.pdf"
    output_png = root / "figures/fig_decision_impact.png"

    merged.sort_values(KEY).to_csv(output_csv, index=False, float_format="%.10f")

    tex = rf"""% Generated by scripts/make_decision_impact.py; do not edit manually.
\begin{{tabular}}{{lr}}
\toprule
Diagnostic & Cells \\
\midrule
Raw corrupted FP8--INT8 gap $>0$ & {raw_positive}/144 \\
Raw corrupted FP8--INT8 gap $<0$ & {raw_negative}/144 \\
Clean-adjusted $\Delta E>0$ & {adjusted_positive}/144 \\
Clean-adjusted $\Delta E<0$ & {adjusted_negative}/144 \\
Raw-positive but adjusted-negative & {positive_to_negative}/144 \\
At least one format below 10 AP & {below_10_cells}/144 \\
At least one format below 5 AP & {below_5_cells}/144 \\
\bottomrule
\end{{tabular}}
"""
    output_tex.write_text(tex, encoding="utf-8")

    fig, axes = plt.subplots(1, 2, figsize=(7.25, 3.25), constrained_layout=True)
    for dataset in DATASET_ORDER:
        block = merged[merged["dataset"] == dataset]
        axes[0].scatter(
            block["raw_corrupt_gap_ap"],
            block["adjusted_interaction_ap"],
            marker=MARKERS[dataset],
            s=27,
            alpha=0.78,
            label=DATASET_LABEL[dataset],
        )
        axes[1].scatter(
            block["min_corrupt_ap"],
            block["adjusted_interaction_ap"],
            marker=MARKERS[dataset],
            s=27,
            alpha=0.78,
            label=DATASET_LABEL[dataset],
        )

    axes[0].axhline(0, linewidth=0.8)
    axes[0].axvline(0, linewidth=0.8)
    axes[0].set_xlabel("Raw corrupted FP8 - INT8 gap (AP points)")
    axes[0].set_ylabel(r"Clean-adjusted interaction $\Delta E$ (AP points)")
    axes[0].set_title("A  Clean adjustment changes the claim", loc="left", fontsize=9.5)
    axes[0].text(
        0.03,
        0.04,
        f"{positive_to_negative}/144 raw-positive cells\nbecome adjusted-negative",
        transform=axes[0].transAxes,
        fontsize=8,
        va="bottom",
    )
    axes[0].legend(frameon=False, fontsize=7.5, ncol=2, loc="upper left")

    axes[1].axhline(0, linewidth=0.8)
    axes[1].axvline(5, linewidth=0.8, linestyle="--")
    axes[1].axvline(10, linewidth=0.8, linestyle=":")
    axes[1].set_xlabel("Lower corrupted AP across the two formats")
    axes[1].set_ylabel(r"Clean-adjusted interaction $\Delta E$ (AP points)")
    axes[1].set_title("B  Interaction needs an absolute-AP guard", loc="left", fontsize=9.5)
    axes[1].text(
        0.97,
        0.04,
        f"{below_10_cells} cells <10 AP\n{below_5_cells} cells <5 AP",
        transform=axes[1].transAxes,
        fontsize=8,
        ha="right",
        va="bottom",
    )

    for ax in axes:
        ax.tick_params(labelsize=8)
        ax.grid(alpha=0.18, linewidth=0.5)

    fig.savefig(output_pdf, bbox_inches="tight")
    fig.savefig(output_png, dpi=320, bbox_inches="tight")
    plt.close(fig)

    audit = {
        "schema_version": 1,
        "status": "valid",
        "scope": "manuscript-level decision-impact diagnostic",
        "formula": "raw_corrupt_gap=(FP8-INT8)_clean+DeltaE=(FP8-INT8)_corrupt",
        "rows": len(merged),
        "summary_ap_points": {
            "mean_clean_gap": float(merged["clean_gap_ap"].mean()),
            "mean_raw_corrupt_gap": float(merged["raw_corrupt_gap_ap"].mean()),
            "mean_adjusted_interaction": float(merged["adjusted_interaction_ap"].mean()),
        },
        "sign_inventory": {
            "raw_positive": raw_positive,
            "raw_negative": raw_negative,
            "adjusted_positive": adjusted_positive,
            "adjusted_negative": adjusted_negative,
            "raw_positive_to_adjusted_negative": positive_to_negative,
            "raw_negative_to_adjusted_positive": negative_to_positive,
        },
        "floor_inventory_cells": {"below_10_ap": below_10_cells, "below_5_ap": below_5_cells},
        "source_sha256": {
            str(contrast_path.relative_to(root)): sha256(contrast_path),
            str(guardrail_path.relative_to(root)): sha256(guardrail_path),
        },
        "generated_sha256": {
            str(output_csv.relative_to(root)): sha256(output_csv),
            str(output_tex.relative_to(root)): sha256(output_tex),
            str(output_pdf.relative_to(root)): sha256(output_pdf),
            str(output_png.relative_to(root)): sha256(output_png),
        },
    }
    output_json.write_text(json.dumps(audit, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(audit["sign_inventory"], sort_keys=True))


if __name__ == "__main__":
    main()
