path: /home/thuan/topic_c_ivc/data/datasets/kitti
train: /home/thuan/topic_c_ivc/manifests/splits/kitti_confirmatory_v1/lists/kitti_confirmatory_v1_train.txt
val: /home/thuan/topic_c_ivc/manifests/splits/kitti_confirmatory_v1/lists/kitti_confirmatory_v1_selection.txt
test: /home/thuan/topic_c_ivc/manifests/splits/kitti_confirmatory_v1/lists/kitti_confirmatory_v1_final.txt
names:
  0: car
  1: van
  2: truck
  3: pedestrian
  4: person_sitting
  5: cyclist
  6: tram
  7: misc
