#!/usr/bin/env python3
"""Generate exactly one deterministic corruption condition and manifest."""
from __future__ import annotations

import argparse
import hashlib
import io
import json
import os
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image, ImageFilter

from topic_c.manifest import manifest_sha256, official_coco_images, sha256_file, validate_manifest


def stable_seed(dataset: str, image_id: int, corruption: str, severity: int) -> int:
    text = f"{dataset}:{image_id}:{corruption}:{severity}".encode("utf-8")
    return int.from_bytes(hashlib.sha256(text).digest()[:8], "big")


def transform(image: Image.Image, corruption: str, parameters: dict[str, float], seed: int) -> Image.Image:
    image = image.convert("RGB")
    if corruption == "jpeg":
        encoded = io.BytesIO()
        image.save(encoded, format="JPEG", quality=int(parameters["quality"]), subsampling=0)
        return Image.open(io.BytesIO(encoded.getvalue())).convert("RGB")
    pixels = np.asarray(image, dtype=np.float32)
    rng = np.random.default_rng(seed)
    if corruption == "gaussian_noise":
        return Image.fromarray(np.clip(pixels + rng.normal(0, parameters["sigma_255"], pixels.shape), 0, 255).astype(np.uint8))
    if corruption == "fog":
        h, w = pixels.shape[:2]
        small = Image.fromarray(rng.integers(0, 256, size=(max(2, h // 32), max(2, w // 32)), dtype=np.uint8), mode="L")
        haze = small.resize((w, h), Image.Resampling.BICUBIC).filter(ImageFilter.GaussianBlur(parameters["blur_radius"]))
        haze = np.asarray(haze, dtype=np.float32)[..., None] / 255.0
        strength = parameters["strength"]
        return Image.fromarray(np.clip(pixels * (1 - strength * haze) + 255 * strength * haze, 0, 255).astype(np.uint8))
    if corruption == "motion_blur":
        import cv2
        kernel_size = int(parameters["kernel"])
        kernel = np.zeros((kernel_size, kernel_size), dtype=np.float32)
        kernel[kernel_size // 2, :] = 1.0 / kernel_size
        angle = int(rng.integers(0, 180))
        matrix = cv2.getRotationMatrix2D((kernel_size / 2 - 0.5, kernel_size / 2 - 0.5), angle, 1.0)
        kernel = cv2.warpAffine(kernel, matrix, (kernel_size, kernel_size))
        kernel /= kernel.sum() + 1e-12
        return Image.fromarray(cv2.filter2D(np.asarray(image), -1, kernel))
    raise ValueError(f"unsupported corruption: {corruption}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", default="coco")
    parser.add_argument("--split", default="val2017")
    parser.add_argument("--annotations", required=True)
    parser.add_argument("--clean-root", required=True)
    parser.add_argument("--cache-root", required=True)
    parser.add_argument("--config", required=True)
    parser.add_argument("--corruption", required=True)
    parser.add_argument("--severity", type=int, choices=(1, 3, 5), required=True)
    parser.add_argument("--manifest-out", required=True)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--resume-validated", action="store_true",
                        help="reuse only pre-existing cache files whose regenerated bytes match exactly; never overwrite")
    args = parser.parse_args()
    manifest_path, cache_root, clean_root = Path(args.manifest_out), Path(args.cache_root), Path(args.clean_root)
    if manifest_path.exists():
        raise SystemExit(f"refusing to overwrite manifest: {manifest_path}")
    config_bytes = Path(args.config).read_bytes()
    config = json.loads(config_bytes)
    try:
        parameters = config["corruptions"][args.corruption]["severity"][str(args.severity)]
    except KeyError as exc:
        raise SystemExit(f"unknown corruption/severity in frozen config: {exc}")
    images = official_coco_images(args.annotations)
    if args.limit:
        images = images[:args.limit]
    records = []
    for item in images:
        image_id, relpath = int(item["id"]), item["file_name"]
        source = clean_root / relpath
        output_relpath = f"{args.corruption}/s{args.severity}/{Path(relpath).with_suffix('.jpg')}"
        destination = cache_root / output_relpath
        seed = stable_seed(args.dataset, image_id, args.corruption, args.severity)
        with Image.open(source) as image:
            result = transform(image, args.corruption, parameters, seed)
        encoded = io.BytesIO()
        result.save(encoded, format="JPEG", quality=int(config["output_encoding"]["quality"]), subsampling=int(config["output_encoding"]["subsampling"]))
        expected_bytes = encoded.getvalue()
        expected_sha256 = hashlib.sha256(expected_bytes).hexdigest()
        if destination.exists():
            if not args.resume_validated:
                raise SystemExit(f"refusing to overwrite cached corruption: {destination}")
            if sha256_file(destination) != expected_sha256:
                raise SystemExit(f"existing cache bytes fail deterministic resume validation: {destination}")
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(dir=destination.parent, suffix=".tmp", delete=False) as handle:
                temporary = Path(handle.name)
                handle.write(expected_bytes)
            try:
                os.replace(temporary, destination)
            finally:
                temporary.unlink(missing_ok=True)
        records.append({"dataset": args.dataset, "image_id": image_id, "source_relpath": relpath, "source_sha256": sha256_file(source), "corruption": args.corruption, "severity": args.severity, "seed": seed, "output_relpath": output_relpath, "sha256": sha256_file(destination), "generator": config["generator"], "generator_version": config["generator_version"], "generator_config_sha256": hashlib.sha256(config_bytes).hexdigest()})
    document = {"schema_version": 1, "dataset": args.dataset, "split": args.split, "expected_image_ids": [item["image_id"] for item in records], "records": records}
    document["manifest_sha256"] = manifest_sha256(document)
    failures = validate_manifest(document, args.annotations, cache_root, clean_root, require_pixels_changed=True)
    if failures:
        raise SystemExit("generated cache failed validation:\n" + "\n".join(failures))
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    marker = manifest_path.with_suffix(manifest_path.suffix + ".complete")
    marker.write_text(document["manifest_sha256"] + "\n", encoding="utf-8")
    print(f"MANIFEST VALID records={len(records)} sha256={document['manifest_sha256']}")


if __name__ == "__main__":
    main()
